# -*- coding: utf-8 -*-
"""6 - Listas de String (Palindromo).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ns3NapaScT9rmhBX_Y_4m1CN7g_aGvuE
"""

palavra = input("Digite uma palavra: ")
palavra = str(palavra) #novo objeto string
nova = palavra[::-1] #inverte a palavra
print(nova)
if palavra == nova:
    print("É um palíndromo") #ex:. ovo ana
else:
    print("Não é um palíndromo")