# -*- coding: utf-8 -*-
"""Impar ou par com multiplo de 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vQn2EYWXNyIXM1iQKfCPEb76YwdAAtVv
"""

numero = int(input("Digite um número: "))
dividir = int(input("Digite um número para dividir: "))

if numero % 4 == 0: 
  print(numero, " Numero par multiplo de 4")
elif numero % 2 == 0:
  print(numero, "Numero par")
else : 
  print(numero, "Numero impar")

if numero % dividir == 0:
  print(numero, "Resultado uniforme ") #igual a 0
else :
  print(numero, "Resultado não uniforme" ) #diferente de 0