# -*- coding: utf-8 -*-
"""Jogo pedra papel tesoura lagarto e mão ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sxNL2NL_OZ0Y1bMxm-VmyKZRCBJxdtcD
"""

from random import randint #geradores de números aleatórios no intervalo especificado
itens = ("Pedra", "Papel", "Tesoura", "Lagarto", "Mao", "Jogada Invalida")

computador = randint(0,4) #0 pedra, 1 papel, 2 tesoura, 3 lagarto e 4 mão

pergunta = int(input('''Escolha uma opcao para se jogar:  

[0] Pedra
[1] Papel
[2] Tesoura
[3] Lagarto
[4] Mao
[] Jogada Invalida

Digite sua escolha: ''')) #''' string em linhas

print("="*30)
print("O computador escolheu: {}".format(itens[computador])) #lista da posição da string
print("O jogador escolheu: {}".format(itens[pergunta]))
print("="*30)

if computador == 0: #computador jogou pedra
    if pergunta == 0:
        print("Empate!")
    elif pergunta == 1:
        print("Papel cobre pedra, você ganhou")
    elif pergunta == 2:
        print("Pedra quebra tesoura, computador ganhou")
    elif pergunta == 3:
        print("Pedra mata lagarto, computador ganhou")
    elif pergunta == 4:
        print("Mão destroi pedra, você ganhou")       
    else:
        print("Operacao invalida")

elif computador == 1: #computador jogou papel
    if pergunta == 0:
        print("Papel cobre pedra, computador ganhou")
    elif pergunta == 1:
        print("Empate!")
    elif pergunta == 2:
        print("Tesoura corta papel, você ganhou")
    elif pergunta == 3:
        print("Lagarto come papel, você ganhou")
    elif pergunta == 4:
        print("Papel desmente a mão, computador ganhou")        
    else:
        print("Operacao invalida")

elif computador == 2: #computador jogou tesoura
    if pergunta == 0:
        print("Pedra quebra tesoura, você ganhou")
    elif pergunta == 1:
        print("Tesoura corta papel, computador ganhou")
    elif pergunta == 2:
        print("Empate!")
    elif pergunta == 3:
        print("Tesoura mata lagarto, computador ganhou") 
    elif pergunta == 4:
        print("Mão esmaga tesoura, você ganhou")         
    else:
        print("Operacao invalida")

elif computador == 3: #computador jogou lagarto
    if pergunta == 0:
        print("Pedra mata lagarto, você ganhou")
    elif pergunta == 1:
        print("Lagarto come papel, computador ganhou")
    elif pergunta == 2:
        print("Tesoura mata lagarto, você ganhou")
    elif pergunta == 3:
        print("Empate!")
    elif pergunta == 4:
        print("Lagarto envenena a mão, computador ganhou")          
    else:
        print("Operacao invalida")

elif computador == 4: #computador jogou mão
    if pergunta == 0:
        print("A mão destroi pedra, computador ganhou")
    elif pergunta == 1:
        print("Papel desmente, você ganhou")
    elif pergunta == 2:
        print("Mão esmaga tesoura, computador ganhou")
    elif pergunta == 3:
        print("Lagarto envenena a mão, você ganhou") 
    elif pergunta == 4:
        print("Empate!")         
    else:
        print("Operacao invalida")        

#else:
    #print("Operacao invalida")