# -*- coding: utf-8 -*-
"""4 - Divisores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJfm7Ld-lZUcEx8GYXuBQ-mGcuwo-5TD
"""

x = int(input("Digite um valor para dividir "))

listRange = list(range(1, x + 1)) #retorna um subconjunto da lista começando em um deslocamento list

divisores = [] #lista em branco para os divisores 

for valor in listRange:
    if x % valor == 0:
        divisores.append (valor) # append >> metodo que anexa um elemento ao final da lista (divisores e valor), no caso printa dentro de um o outro

print(divisores)