# -*- coding: utf-8 -*-
"""5 - Soluções de sobreposição de lista.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VklRAxqnEIbYq7EWDCwCV6zawoQAoln9
"""

x = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 90,"m", 102] 
y = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, "m"]
z = []

for a in x:
  if a in y and a not in z: 
    z.append(a) #valores iguais em x e y devem serem printados em z[]
 

print(z)