# -*- coding: utf-8 -*-
"""7 - Compreensões de lista (num pares de uma lista).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dUz_fq2fQi57E-38psVIM_43yX548sp_
"""

lista = [1,3,2,4,5,8,13,21,34,55,89,60,68,101,104]
nova_lista = [num for num in lista if num % 2 == 0] 
print(nova_lista)