# -*- coding: utf-8 -*-
"""9 - Jogo de adivinhação um.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MOw2F9P5h50q5dnbnDaFqLe3BcU8-Ptj
"""

import random #gerar um numero inteiro aleatorio

num = random.randint (1,9) #intervalo de 1 a 9
contagem = 0
palpite = 0


while palpite != num and palpite != "sair":
    palpite = input("Dê o seu palpite? ")  #adivinhe o numero, dê um palpite
    
    if palpite == "sair": #adivinhar
        break
    
    palpite = int(palpite) #novo objeto string a palpite
    contagem += 1          #conta o numero de tentatitavas
    
    if palpite < num:
        print("Baixo!")
    elif palpite > num:
        print("Alto!")
    else:
        print("Você acertou, parabéns!")
        print("Você precisou de", contagem, "tentativas")