# -*- coding: utf-8 -*-
"""1 - Entrada de personagem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17tWddfltVqnuOJxMWvm3KtYFfHKy1QQg
"""

nome = input("Qual seu nome ? ")
idade = int(input("Qual sua idade ? "))
anofinal = str((2020 - idade)+100) #deve-se usar o str pois ele indica que o inteiro deve primeiro ser convertido em uma string antes de poder ser concatenado
print(nome + " você terá 100 anos em : "+ anofinal)