# -*- coding: utf-8 -*-
"""E1_Rasboticas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wqUJbl7JPyeWAJH9O-1G8a6pojC9SVo2
"""

import numpy as np

A = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]] #formar matriz 4X4
B = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
for l in range(0,4):
  for c in range(0,4):
    A[l][c] = int(input())

for l in range(0,4):
  for c in range(0,4):
    B[l][c] = int(input())

for l in range(0,1):
  for c in range(0,1):
    print(A,B)

#1-Soma
#2-Subtração
#3-Multiplicação
#4-Divisão
#5-Produto entre as duas matrizes
#6-Concatenação

operacao = int(input())

if operacao == 1:
  array1 = np.array([A])
  array2 = np.array([B])
  matriz = np.add(array1, array2)
  print(matriz)  

elif operacao == 2:
  array1 = np.array([A])
  array2 = np.array([B])
  print(array1-array2)


elif operacao == 3:
  array1 = np.array([A])
  array2 = np.array([B])
  matriz = np.multiply(array1, array2)
  print(matriz)

elif operacao == 3:
  array1 = np.array([A])
  array2 = np.array([B])
  print(array1/array2)

elif operacao == 5:
  array1 = np.array([A])
  array2 = np.array([B])
  #matriz = np.mat(array1, array2)
  print(array1@array2)
  
else operacao == 6:
  array1 = np.array([A])
  array2 = np.array([B])
  matriz = np.concatenate((array1, array2), axis=2)
  print(matriz)