# -*- coding: utf-8 -*-
"""E1Q2_Rasboticas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VnZA_ihJ4RneC9T8tcqZx8lMAB4XXQ_m
"""

listaA = [[], [], []]
for c1 in range(0, 3):
    for c2 in range(0, 3):
        n = int(input())
        listaA[c1].append(n)
print(listaA)

listaB = np.sin(listaA)
print(listaB)