# -*- coding: utf-8 -*-
"""E1Q3Rasboticas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y35qh-YtHVaKhWrz74N8tlqh_f9K1Ynr
"""

import math                   
 
a = float(input())
tentativa = []
print("Seno: {:.3f}".format(math.sin(math.radians(a))))
print("Cosseno: {:.3f}".format(math.cos(math.radians(a))))
while (a != tentativa):
  tentativa = float(input())
else:  
  print("Finish")